# Generated by Django 4.1.7 on 2023-05-30 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0015_alter_enrollment_price_alter_membershipplan_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.DeleteModel(
            name='Trainer',
        ),
    ]
